# Setting up automated tests for the framework
os: linux
dist: bionic
language: php
env:
  global:
    - FRAMEWORK_VERSION=1.6.68 # <current version>
    - PHPHUNIT_VERSION=>=9.0.0

jobs:
  fast_finish: true
  include:
    - php: 7.1
      env: PHPHUNIT_VERSION=>=6.0.0
    - php: 7.2
      env: PHPHUNIT_VERSION=^8.0.0
    - php: 7.3
    - php: 7.4
    - php: 8.0
    - php: 8.0.1
    - php: 8.0.2
    - php: 8.0.9
    - php: 8.1.0
    - php: nightly

install:
  - composer require phphleb/framework $FRAMEWORK_VERSION
  - composer require phpunit/phpunit $PHPHUNIT_VERSION
  - composer require phphleb/tests

script:
  - vendor/bin/phpunit vendor/phphleb/tests/
  - php console --version